# get users
GET http://localhost:5000/users


# clear database
###
DELETE http://localhost:5000/users


# get user 
###
GET http://localhost:5000/users/64f082a3048d2604264bdbe4

# get profile
###
http://localhost:5000/users/profile

# create user 
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Admin Admin", 
    "email": "admin@gmail.com",
    "password": "password",
    "isAdmin": true 
}

# login user
###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}


# logout user
###
POST http://localhost:5000/users/logout

#get produts
###
GET http://localhost:5000/products 

# clear products
###
DELETE http://localhost:5000/products

# create cart
###
POST http://localhost:5000/carts/create
Content-Type: application/json

{
    "products": [
        {
            "productId": "629d0e257fbe7eb52ddbabec",
            "quantity": 5
        },
        {
            "productId": "629d0e257fbe7eb52ddbabef",
            "quantity": 2
        }
    ]
}

# get carts
###
GET http://localhost:5000/carts


# get cart
###
http://localhost:5000/carts/650e839f960a73e07045cd7a